-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-08-29 19:47:56 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE book_copy PURGE;

DROP TABLE book_detail PURGE;

DROP TABLE borrower PURGE;

DROP TABLE branch PURGE;

DROP TABLE loan PURGE;

DROP TABLE manager PURGE;

DROP TABLE reserve PURGE;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE book_copy (
    branch_code          NUMBER(2) NOT NULL,
    bc_id                NUMBER(6) NOT NULL,
    bc_purchase_price    NUMBER(7, 2) NOT NULL,
    bc__counter_reserve  CHAR(1) NOT NULL,
    book_call_no         VARCHAR2(20) NOT NULL
    CONSTRAINT book_copy_pk PRIMARY KEY ( bc_id, branch_code );
);


CREATE TABLE book_detail (
    book_call_no         VARCHAR2(20) NOT NULL,
    book_title           VARCHAR2(100) NOT NULL,
    book_classification  CHAR(1) NOT NULL,
    book_no_pages        NUMBER(4) NOT NULL,
    book_pub_year        DATE NOT NULL,
    book_edition         VARCHAR2(3)
    CONSTRAINT book_detail_pk PRIMARY KEY ( book_call_no );
);


CREATE TABLE borrower (
    bor_no        NUMBER(6) NOT NULL,
    bor_fname     VARCHAR2(59) NOT NULL,
    bor_lname     VARCHAR2(50) NOT NULL,
    bor_street    VARCHAR2(80) NOT NULL,
    bor_suburb    VARCHAR2(50) NOT NULL,
    bor_postcode  CHAR(4) NOT NULL,
    branch_code   NUMBER(2) NOT NULL
    CONSTRAINT borrower_pk PRIMARY KEY ( bor_no );
);


CREATE TABLE branch (
    branch_code         NUMBER(2) NOT NULL,
    branch_name         VARCHAR2(50) NOT NULL,
    branch_address      VARCHAR2(100) NOT NULL,
    branch_contact_no   CHAR(10) NOT NULL,
    branch_count_books  NUMBER(5) NOT NULL,
    man_id              NUMBER(2) NOT NULL,
    CONSTRAINT branch_pk PRIMARY KEY ( branch_code ),
    CONSTRAINT branch_contact_no_uq UNIQUE ( branch_contact_no )

);


CREATE TABLE loan (
    branch_code              NUMBER(2) NOT NULL,
    bc_id                    NUMBER(6) NOT NULL,
    loan_date_time           DATE NOT NULL,
    loan_due_date            DATE NOT NULL,
    loan_actual_return_date  DATE,
    bor_no                   NUMBER(6) NOT NULL
    CONSTRAINT loan_pk PRIMARY KEY ( loan_date_time,
                                         bc_id,
                                         branch_code );
);


CREATE TABLE manager (
    man_id          NUMBER(2) NOT NULL,
    man_fname       VARCHAR2(50) NOT NULL,
    man_lname       VARCHAR2(50) NOT NULL,
    man_contact_no  CHAR(10) NOT NULL
    CONSTRAINT manager_pk PRIMARY KEY ( man_id );
);


CREATE TABLE reserve (
    reserve_id                NUMBER(6) NOT NULL,
    branch_code               NUMBER(2) NOT NULL,
    bc_id                     NUMBER(6) NOT NULL,
    reserve_date_time_placed  DATE NOT NULL,
    bor_no                    NUMBER(6) NOT NULL
    CONSTRAINT reserve_pk PRIMARY KEY ( reserve_id );
    CONSTRAINT reserve_uk UNIQUE ( bc_id,
                                       branch_code,
                                       reserve_date_time_placed );
);


ALTER TABLE loan
    ADD CONSTRAINT book_copy_loan FOREIGN KEY ( bc_id,
                                          branch_code )
        REFERENCES book_copy ( bc_id,
                               branch_code );

ALTER TABLE loan
    ADD CONSTRAINT borrower_loan FOREIGN KEY ( bor_no )
        REFERENCES borrower ( bor_no );

ALTER TABLE book_copy
    ADD CONSTRAINT book_detail_book_copy FOREIGN KEY ( book_call_no )
        REFERENCES book_detail ( book_call_no );

ALTER TABLE book_copy
    ADD CONSTRAINT branch_book_copy FOREIGN KEY ( branch_code )
        REFERENCES branch ( branch_code );

ALTER TABLE reserve
    ADD CONSTRAINT book_copy_reserve FOREIGN KEY ( bc_id,
                                             branch_code )
        REFERENCES book_copy ( bc_id,
                               branch_code );

ALTER TABLE branch
    ADD CONSTRAINT manager_branch FOREIGN KEY ( man_id )
        REFERENCES manager ( man_id );

ALTER TABLE borrower
    ADD CONSTRAINT branch_borrower FOREIGN KEY ( branch_code )
        REFERENCES branch ( branch_code );

ALTER TABLE reserve
    ADD CONSTRAINT borrower_reserve FOREIGN KEY ( bor_no )
        REFERENCES borrower ( bor_no );